blank_issues_enabled: false
contact_links:
  - name: 1 FORM-NAME
    url: ./FORM-NAME.yml
    about: Test FORM-NAME 1
  - name: 2 FORM-NAME 
    url: FORM-NAME.yml
    about: Test FORM-NAME 2
  - name: 3 FORM-NAME 
    url: ./.github/ISSUE_TEMPLATE/FORM-NAME.yml
    about: Test FORM-NAME 3
  - name: 4 FORM-NAME 
    url: /.github/ISSUE_TEMPLATE/FORM-NAME.yml
    about: Test FORM-NAME 4
  - name: GitHub Community Support
    url: https://github.com/orgs/community/discussions
    about: Please ask and answer questions here.
  - name: GitHub Security Bug Bounty
    url: https://bounty.github.com/
    about: Please report security vulnerabilities here.
